In [1]:
import numpy as np

# 行列 A と B を定義
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積を計算
C = np.dot(A, B)

# 結果の行列を表示
print("行列の積 C:\n", C)

# 行列の最大要素を求める
max_element = np.max(C)
print("行列 C の要素の最大値:", max_element)

行列の積 C:
 [[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列 C の要素の最大値: 47
